# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RestfulTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RestfulTest
pod "Alamofire"
  target 'RestfulTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RestfulTestUITests' do
    # Pods for testing
  end

end
